# Generated by Django 4.2 on 2024-05-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_name', models.CharField(max_length=50)),
                ('special_description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'special',
                'verbose_name_plural': 'specials',
            },
        ),
    ]
