# Generated by Django 4.2 on 2024-05-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='special_image',
            field=models.ImageField(default=None, upload_to='uploads/(%Y/%m/%d/)'),
            preserve_default=False,
        ),
    ]
