# Generated by Django 4.2 on 2024-05-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0002_special_special_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='special_image',
            field=models.ImageField(upload_to='special_images/(%Y-%m-%d)'),
        ),
    ]
