# Generated by Django 4.2 on 2024-05-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0003_alter_special_special_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef_name', models.CharField(max_length=100)),
                ('chef_description', models.CharField(max_length=255)),
                ('twitter_link', models.URLField(max_length=150)),
                ('facebook_link', models.URLField(max_length=150)),
                ('linkedin_link', models.URLField(max_length=150)),
            ],
            options={
                'verbose_name': 'Chef',
                'verbose_name_plural': 'Chefs',
            },
        ),
    ]
